title: Malwina Kotowicz # your name (or website title) here
logo: "/images/mal_kot.png" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Hi there! I'm Malwina, a biotechnologist with experience in nano/biomaterials for drug delivery, biomedicine and molecular genetics. 
  <br><br>
  I have a strong interest in machine learning, artificial intelligence, robotics and psychology.
  <br><br>
  <a href="https://www.linkedin.com/in/malwina-kotowicz/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
