title: Malwina Kotowicz # your name (or website title) here
logo: "/images/mal_kot.png" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Hi there! It's Malwina. I write programs to make things work. 
  <br><br>
  I'm a biotechnologist who fell in love with robots. I use Python to bring my ideas to life. 
  <br><br>
  <a href="https://www.linkedin.com/in/malwina-kotowicz/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
